# Generated by Django 4.2 on 2023-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
