# Generated by Django 4.2 on 2023-04-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_office', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
