# Generated by Django 4.2 on 2023-04-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_office', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
