# Generated by Django 4.2 on 2023-04-28 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_office', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Организации',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='User_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_office.office', verbose_name='Организации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_office', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Организации',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ManyToManyField(through='users_office.User_office', to='users_office.office'),
        ),
    ]
