# Generated by Django 4.2 on 2023-04-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_office', '0006_office_user_office_user_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_office',
            options={'verbose_name': 'Юзер и Организации', 'verbose_name_plural': 'Юзер и  Организация'},
        ),
    ]
